os:
  - osx
osx_image: xcode11.3
language: swift
script:
  - swift test --package-path ./RHBFoundation
  - swift test --package-path ./RHBCoreData
  - swift test --package-path ./RHBContacts
notifications:
  email:
    on_success: change
    on_failure: change
